fix command line problems and actually show output
jbossws/jaxws-tools-maven-plugin pull request #9
Opened 2021-03-02 16:27 UTC by alexyz

Fixed this problem with "wsconsume" on Windows:
[ERROR] 'C:\Program' is not recognized as an internal or external command,
[ERROR] operable program or batch file.

2021-09-10 19:40 UTC, arnold-maderthaner commented
please merge this pull request as I also have the same issue in 1.2.3-final version

2021-09-14 17:17 UTC, rsearls requested changes

2021-09-14 17:17 UTC, rsearls commented on pom.xml
> -  <version>1.2.4-SNAPSHOT</version>
Return to the 1.2.4-SNAPSHOT version of the POM.

2021-09-14 17:17 UTC, rsearls commented on pom.xml
> +          <streamLogs>true</streamLogs>
We do not want debugging information printed to the console by default.  
Comment out line 100 and add a comment the enabling this properly will print information to the console.

2021-09-14 17:17 UTC, rsearls commented on src/main/java/org/jboss/ws/plugins/tools/WSContractDelegate.java
> +//      MavenLogStreamConsumer out = new MavenLogStreamConsumer(log, Type.OUTPUT);
Remove commented lines 85-87

2021-09-14 17:17 UTC, rsearls commented on src/main/java/org/jboss/ws/plugins/tools/WSContractDelegate.java
> +//      MavenLogStreamConsumer out = new MavenLogStreamConsumer(log, Type.OUTPUT);
Remove commented lines 134-136

2021-09-14 17:17 UTC, rsearls commented on src/main/java/org/jboss/ws/plugins/tools/WSContractDelegate.java
> +//      StringBuilder command = new StringBuilder();
Remove commented lines 237-243

2021-09-14 17:17 UTC, rsearls commented on src/main/java/org/jboss/ws/plugins/tools/WSContractDelegate.java
> +//      StringBuilder command = new StringBuilder();
Remove commented lines 280-286

2021-09-14 17:17 UTC, rsearls commented on pom.xml
> +          <streamLogs>true</streamLogs>
I have created jira https://issues.redhat.com/browse/JBWS-4228 for this code change.
This allows us to better track changes over time.
Please amend your commit comment to start with "[JBWS-4228]"

2021-09-15 14:31 UTC, alexyz commented
I tried to clean up this PR, but it failed in my local test case (Java 11) - building a slight variation of this project: https://github.com/dcm4che/dcm4chee-xds/tree/master/dcm4chee-xds2-infoset

After "run consumer out of process" I get various NoClassDefFoundError caused by bad classpath building in org.jboss.ws.plugins.tools.AbstractToolsMojo#getRequiredPluginDependencyPaths:

[WARNING] consumer: Caused by: java.lang.ClassNotFoundException: org.jboss.ws.api.tools.WSContractConsumer
This can be fixed by adding "jbossws-api".equals(s.getArtifactId())

[WARNING] consumer: Caused by: java.lang.ClassNotFoundException: org.jboss.logging.Messages
This doesn't have an obvious fix. org.jboss.logging:jboss-logging is a transitive and provided dependency of org.jboss.ws:jbossws-api. So I guess it's never delivered to the plugin? 

After adding this as an explicit dependency, I get this:
[WARNING] consumer: Caused by: java.lang.ClassNotFoundException: org.jboss.ws.tools.jaxws.impl.SunRIConsumerFactoryImpl
I don't even know what provides this.

I made some changed and pushed them but I think the plugin has more fundamental problems. I'm not interested in using the plugin anymore so someone else can take this over.

2021-09-15 17:04 UTC, rsearls commented
What is your variation to https://github.com/dcm4che/dcm4chee-xds/tree/master/dcm4chee-xds2-infoset
I would like to investigate the nature of the failure.

I integrated your changes  into  a branch of jaxws-tools-maven-plugin.  It builds and runs the tests successfully.  I have submitted PR https://github.com/jbossws/jaxws-tools-maven-plugin/pull/10

2021-09-17 13:46 UTC, alexyz commented
Sorry forgot to reply sooner.
The only real changes for the infoset project are to the pom:
Removing the parent (it's virtually independent of the rest of DCM4CHE)
Changing the WS plugin name and version to the latest

2022-03-18 12:14 UTC, rsearls commented
Closing this PR without merging.  PR https://github.com/jbossws/jaxws-tools-maven-plugin/pull/10
appears to address the issue.

2022-03-18 12:14 UTC, closed without merging